### ISSUE TITLE
Swirl script "index_email_opensearch.py" yields "AttributeError: 'ArgumentParser' object has no attribute 'parse'"

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#97]
Download and prepare the OpenSearch Search provider/Connector and the Enron email data set.

Run the scripts/index_email_opensearch.py script to index this data set as outlined in the Swirl documentation, and Swirl returns the following error:
```
python scripts/index_email_opensearch.py -i email -u admin -p password ../opensearch/emails.csv 
Indexing...
Traceback (most recent call last):
  File "/Users/erikspears/Development/swirl182/scripts/index_email_opensearch.py", line 96, in <module>
    main(sys.argv)
  File "/Users/erikspears/Development/swirl182/scripts/index_email_opensearch.py", line 63, in main
    dt = parser.parse(s_date)
         ^^^^^^^^^^^^
AttributeError: 'ArgumentParser' object has no attribute 'parse'
```

**Comment by sidprobstein** [comment]
Bad programming... the fix is in main now

**Comment by erikspears** [comment]
For the record, we validated this fix last evening; the included script worked as expected for ingesting and indexing the CSV version of the Enron email corpus.
